# Generated by Django 5.1 on 2024-08-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_files_size_alter_fileversion_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileversion',
            name='file_id',
        ),
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccessControl',
        ),
        migrations.DeleteModel(
            name='FileVersion',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
