# Generated by Django 5.1 on 2024-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_fileversion_file_id_alter_files_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='files',
            name='size',
        ),
        migrations.RemoveField(
            model_name='files',
            name='user_id',
        ),
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default='empty', upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
