# Generated by Django 5.1 on 2024-08-20 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_rename_description_files_comment_remove_files_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file_path',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='files',
            name='download_link',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='size',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
