POST http://127.0.0.1:8000/files/
Content-Type: application/json

{
  "file_name": "только что",
  "user_id": 10
}

###

GET http://127.0.0.1:8000/files/

###

GET http://127.0.0.1:8000/get_link_for_file/16/ 

###

DELETE http://127.0.0.1:8000/files/10/

###

GET http://127.0.0.1:8000/users/1/

###

POST http://127.0.0.1:8000/check_password/
Content-Type: application/json

{
  "login": "123",
  "password": "123"
}

###

POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
  "name": "nikita",
  "login": "-nikita-",
  "password": "1234",
}

###

GET http://127.0.0.1:8000/get_files_user/10/


###

GET http://127.0.0.1:8000/download_file/35/