# Generated by Django 5.1 on 2024-08-25 11:31
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_data(apps, schema_editor):
    User = apps.get_model('server', 'User')
    username = "admin"
    User(
        username=username,
        # first_name="Admin_1",
        # last_name="Admin_2",
        email="admin@email.com",
        password=make_password("admin"),
        is_staff=True,
        is_active=True,
        is_superuser=True,
        folder_name=f'{username}_folder'
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_data)]