# Generated by Django 5.1 on 2024-12-20 18:59

import django.core.validators
import server.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_auto_20240825_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                default="uploads/",
                upload_to=server.models._create_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "tiff",
                            "jpg",
                            "png",
                            "jpeg",
                            "pdf",
                            "doc",
                            "docx",
                            "gif",
                            "exe",
                        ]
                    )
                ],
                verbose_name="File",
            ),
        ),
    ]
