# Generated by Django 5.1 on 2025-02-05 17:10

import django.core.validators
import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='uploads/', 
            upload_to=server.models._create_directory_path, 
            validators=[django.core.validators.FileExtensionValidator(
                [
                    'tiff', 
                    'jpg', 
                    'png', 
                    'jpeg', 
                    'pdf', 
                    'doc', 
                    'docx', 
                    'gif', 
                    'json'
                ])], 
                verbose_name='File'),
        ),
    ]
