# Generated by Django 5.1.4 on 2025-01-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycloud", "0004_file_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
