# Generated by Django 5.1.4 on 2025-01-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
