# Generated by Django 5.1.4 on 2025-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_link',
            field=models.CharField(max_length=200),
        ),
    ]
